---
  # ================= Auto Config Planetmina  ================== #
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: script
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: 0.0.0.0:7874
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.24.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.netflix.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    fake-ip-filter:
    - "+.pool.ntp.org"
    - ntp7.*.com
    - ntp6.*.com
    - ntp5.*.com
    - ntp4.*.com
    - ntp3.*.com
    - ntp2.*.com
    - ntp1.*.com
    - ntp.*.com
    - time7.*.com
    - time6.*.com
    - time5.*.com
    - time4.*.com
    - time3.*.com
    - time2.*.com
    - time1.*.com
    - time.*.apple.com
    - time.*.edu.cn
    - time.*.gov
    - time.*.com
    - "*.home.arpa"
    - "*.local"
    - "*.test"
    - "*.localhost"
    - "*.invalid"
    - "*.example"
    - "*.localdomain"
    - time1.cloud.tencent.com
    - "*.ntp.org"
    - "*.time.edu"
    - "*.lan"
    - "*.ntp.org.cn"
    - "*.time.edu.cn"
    - "+.*"
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - https://dns.adguard-dns.com:3000/dns-query
  - tls://dns.adguard-dns.com:3000
  - 74.82.42.42
  - 103.133.222.202
  default-nameserver:
  - 74.82.42.42
  - 103.133.222.202
  - 8.8.8.8
  - 1.1.1.1
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - "+.google.com"
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  # ================= Auto Proxy-Providers  ================== #
proxy-providers:
  AKUN1:
    type: http
    path: "./proxy_provider/akun1.yaml"
    url: http://bit.ly/3IsSA5k
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  AKUN2:
    type: http
    path: "./proxy_provider/akun2.yaml"
    url: http://bit.ly/3GQrZh6
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 99
  # ================= Auto Proxy-Grups  ================== #
proxy-groups:
- name: PLANETMINA-AUTO
  type: select
  disable-udp: false
  proxies:
  - AKUN-SELECT
  - AKUN-PING
  - AKUN-FALLBACK
  - AKUN-LOADBALANCE
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth0
- name: AKUN-SELECT
  type: select
  disable-udp: false
  use:
  - AKUN1
  - AKUN2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth1
- name: AKUN-PING
  type: url-test
  disable-udp: false
  use:
  - AKUN1
  - AKUN2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth1
- name: AKUN-FALLBACK
  type: fallback
  disable-udp: false
  use:
  - AKUN1
  - AKUN2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth1
- name: AKUN-LOADBALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - AKUN1
  - AKUN2
  url: http://www.gstatic.com/generate_204
  interval: '99'
  interface-name: eth1
- name: WHATSAPP
  type: select
  disable-udp: false
  proxies:
  - AKUN-SELECT
  - AKUN-PING
  - AKUN-FALLBACK
  - AKUN-LOADBALANCE
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '99'
- name: GAMING
  type: select
  disable-udp: false
  proxies:
  - AKUN-SELECT
  - AKUN-PING
  - AKUN-FALLBACK
  - AKUN-LOADBALANCE
  - DIRECT
  url: http://www.gstatic.com/generate_204
  interval: '99'
  # ================= Auto Rule-Providers  ================== #
rule-providers:
  Game:
    type: http
    behavior: domain
    path: ./rule_provider/game.yaml
    url: https://bit.ly/pmautorulegame
    interval: 3600
  Sosmed:
    type: http
    behavior: domain
    path: ./rule_provider/sosmed.yaml
    url: https://bit.ly/pmautorulesosmed
    interval: 3600
  Stream:
    type: http
    behavior: domain
    path: ./rule_provider/stream.yaml
    url: https://bit.ly/pmautorulestream
    interval: 3600
  Olshop:
    type: http
    behavior: domain
    path: ./rule_provider/olshop.yaml
    url: https://bit.ly/pmautoruleolshop
    interval: 3600
  Bank:
    type: http
    behavior: domain
    path: ./rule_provider/bank.yaml
    url: https://bit.ly/pmautorulebank
    interval: 3600
  Whatsapp:
    type: http
    behavior: domain
    path: ./rule_provider/whatsapp.yaml
    url: https://bit.ly/pmautorulewhatsapp
    interval: 3600
script:
  code: |
    def main(ctx, metadata):
        ruleset_action = {"Game": "GAMING",
            "Sosmed": "PLANETMINA-AUTO",
            "Stream": "PLANETMINA-AUTO",
            "Olshop": "PLANETMINA-AUTO",
            "Bank": "PLANETMINA-AUTO",
            "Whatsapp": "WHATSAPP",
          }

        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == "21,22,23,53,80,443,8443":
                ctx.log('[Script] matched QUIC traffic use PLANETMINA-AUTO')
                return "PLANETMINA-AUTO"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        port_list = [21, 22, 23, 53, 80, 81, 123, 443, 853, 5353, 8000, 8008, 8080, 8081, 8090, 8443, 8888, 9993]
        if port not in port_list:
            ctx.log('[Script] not common port use GAMING')
            return "GAMING"

        if metadata["dst_ip"] == "":
            return "DIRECT"

        for ruleset in ruleset_action:
            if ctx.rule_providers[ruleset].match(metadata):
                return ruleset_action[ruleset]

        code = ctx.geoip(metadata["dst_ip"])
        if code == "ID":
            ctx.log('[Script] Geoip ID')
            return "PLANETMINA-AUTO"

        ctx.log('[Script] PLANETMINA-AUTO')
        return "PLANETMINA-AUTO"
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,Game,GAMING
- RULE-SET,Sosmed,PLANETMINA-AUTO
- RULE-SET,Stream,PLANETMINA-AUTO
- RULE-SET,Olshop,PLANETMINA-AUTO
- RULE-SET,Bank,PLANETMINA-AUTO
- RULE-SET,Whatsapp,WHATSAPP
- GEOIP,ID,PLANETMINA-AUTO
- MATCH,PLANETMINA-AUTO
tun:
  enable: true
  stack: system
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fake-ip: true
secret: 'root'
bind-address: "*"
experimental:
  sniff-tls-sni: true
authentication:
- Clash:hckUjOup
